apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: firstgrpcclient-project1
  name: firstgrpcclient-project1
spec:
  selector:
    matchLabels:
      app: firstgrpcclient-project1
  replicas: 1
  template:
    metadata:
      labels:
        app: firstgrpcclient-project1
    spec:
      containers:
        - name: firstgrpcclient-project1
          image: firstgrpcclient-project1
          imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: firstgrpcclient-project1
  labels:
    app: firstgrpcclient-project1
spec:
  selector:
    app: firstgrpcclient-project1
  ports:
    - port: 50102